#________________________________________
#
#

include				$(MAKE_PATH)/common.mk

BUILD_ARTIFACT			= $(TARGET_BUILD_PATH)/.libs/$(TARGET_NAME).a
CONFIGURE_ARTIFACT		= $(TARGET_BUILD_PATH)/Makefile
EXTRACT_ARTIFACT		= $(CONFIGURE_ARTIFACT).in
INSTALL_ARTIFACT		= $(INSTALL_LIB_PATH)/$(TARGET_NAME).a
TARGET_BUILD_PATH		= $(BUILD_PATH)/$(TARGET_NAME_VERSION)
TARGET_NAME			= libevent
TARGET_NAME_VERSION		= $(TARGET_NAME)-$(TARGET_VERSION)-stable
TARGET_TARBALL_NAME		= $(TARGET_NAME_VERSION).tar.gz
TARGET_TARBALL_PATH		= $(SOURCE_PATH)/$(TARGET_TARBALL_NAME)
TARGET_VERSION			= 2.0.21

#________________________________________
#
#

$(TARGET_NAME): $(INSTALL_ARTIFACT)

$(EXTRACT_ARTIFACT): $(TARGET_TARBALL_PATH)
	tar zxf $< -C $(BUILD_PATH)

$(CONFIGURE_ARTIFACT): $(EXTRACT_ARTIFACT)
	cd $(TARGET_BUILD_PATH); ./configure --prefix=$(INSTALL_PATH) --enable-static

$(BUILD_ARTIFACT): $(CONFIGURE_ARTIFACT)
	cd $(TARGET_BUILD_PATH); make

$(INSTALL_ARTIFACT): $(BUILD_ARTIFACT)
	cd $(TARGET_BUILD_PATH); make install

clean:
	-rm -rf $(TARGET_BUILD_PATH)

#
#
#

